Repository greystation14/GreyStation14, pull requests merged in 2024-09, with the labels that each got.

#317 Rename Application
  Resources/manifest.yml
Labels: No C#

#319 Merge Upstream 9.3.24
  Resources/Changelog/Changelog.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/secdrobe.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/theater.yml
Labels: No C#

#328 Merge Upstream 9.10.24
  Content.Server/Atmos/EntitySystems/GasTankSystem.cs
  Content.Server/Revenant/EntitySystems/RevenantSystem.cs
  Content.Shared/CCVar/CCVars.cs
  Content.Shared/Revenant/Components/RevenantComponent.cs
  Resources/Changelog/Changelog.yml
  Resources/ConfigPresets/WizardsDen/wizardsDen.toml
  Resources/Maps/Shuttles/ShuttleEvent/bang.yml
  Resources/Maps/Shuttles/ShuttleEvent/drone.yml
  Resources/Maps/Shuttles/ShuttleEvent/hook.yml
  Resources/Maps/Shuttles/ShuttleEvent/instigator.yml
  Resources/Maps/Shuttles/ShuttleEvent/manowar.yml
  Resources/Maps/Shuttles/ShuttleEvent/raider.yml
  Resources/Maps/Shuttles/ShuttleEvent/scooner.yml
  Resources/Maps/meta.yml
  Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
  Resources/Prototypes/Entities/Clothing/Head/helmets.yml
  Resources/Prototypes/Entities/Objects/Devices/Circuitboards/Machine/production.yml
  Resources/Prototypes/Entities/Structures/Machines/lathe.yml
  Resources/Prototypes/Entities/Structures/Wallmounts/screen.yml
  Resources/Prototypes/GameRules/unknown_shuttles.yml
  Resources/Prototypes/Recipes/Lathes/electronics.yml
  Resources/Prototypes/Research/industrial.yml
  Resources/Prototypes/Shuttles/shuttle_incoming_event.yml
  Resources/Textures/Structures/Furniture/Tables/reinforced.rsi/state_7.png
  Resources/Textures/Structures/Walls/solid.rsi/meta.json
  Resources/Textures/Structures/Walls/solid.rsi/reinf_construct-0.png
  Resources/Textures/Structures/Walls/solid.rsi/reinf_construct-1.png
  Resources/Textures/Structures/Walls/solid.rsi/reinf_construct-2.png
  Resources/Textures/Structures/Walls/solid.rsi/reinf_construct-3.png
  Resources/Textures/Structures/Walls/solid.rsi/reinf_construct-4.png
  Resources/Textures/Structures/Walls/solid.rsi/reinf_construct-5.png
  Resources/Textures/Structures/Walls/solid.rsi/reinf_over0.png
  Resources/Textures/Structures/Walls/solid.rsi/reinf_over1.png
  Resources/Textures/Structures/Walls/solid.rsi/reinf_over2.png
  Resources/Textures/Structures/Walls/solid.rsi/reinf_over3.png
  Resources/Textures/Structures/Walls/solid.rsi/reinf_over4.png
  Resources/Textures/Structures/Walls/solid.rsi/reinf_over5.png
  Resources/Textures/Structures/Walls/solid.rsi/reinf_over6.png
  Resources/Textures/Structures/Walls/solid.rsi/rgeneric.png
  Resources/Textures/Structures/Walls/solid.rsi/solid0.png
  Resources/Textures/Structures/Walls/solid.rsi/solid1.png
  Resources/Textures/Structures/Walls/solid.rsi/solid2.png
  Resources/Textures/Structures/Walls/solid.rsi/solid3.png
  Resources/Textures/Structures/Walls/solid.rsi/solid4.png
  Resources/Textures/Structures/Walls/solid.rsi/solid5.png
  Resources/Textures/Structures/Walls/solid.rsi/solid6.png
  Resources/Textures/Structures/Walls/solid.rsi/solid7.png
Labels: Changes: Sprites, Changes: Map

#329 Trooper Time
  Resources/Prototypes/Entities/Clothing/Head/hats.yml
  Resources/Prototypes/Loadouts/Jobs/Security/security_officer.yml
  Resources/Prototypes/Loadouts/loadout_groups.yml
  Resources/Textures/GreyStation/Clothing/Head/Hats/security_trooper_hat.rsi/equipped-HELMET.png
  Resources/Textures/GreyStation/Clothing/Head/Hats/security_trooper_hat.rsi/icon.png
  Resources/Textures/GreyStation/Clothing/Head/Hats/security_trooper_hat.rsi/inhand-left.png
  Resources/Textures/GreyStation/Clothing/Head/Hats/security_trooper_hat.rsi/inhand-right.png
  Resources/Textures/GreyStation/Clothing/Head/Hats/security_trooper_hat.rsi/meta.json
Labels: No C#, Changes: Sprites

#334 Commie Shuttle Added
  Resources/Maps/Shuttles/ShuttleEvent/commieshuttle.yml
Labels: No C#, Changes: Map

#332 Tony's Knuckledusters and Mask
  Resources/Audio/GreyStation/Misc/drawknife.ogg
  Resources/Audio/GreyStation/Misc/hit.ogg
  Resources/Audio/GreyStation/Misc/licenses.txt
  Resources/Audio/GreyStation/Misc/pickupweapon.ogg
  Resources/Audio/GreyStation/Misc/punch.ogg
  Resources/Prototypes/GreyStation/Entities/Clothing/Head/hats.yml
  Resources/Prototypes/GreyStation/Entities/Objects/Weapons/Melee/knuckle_dusters.yml
  Resources/Prototypes/GreyStation/SoundCollections/knuckleduster.yml
  Resources/Textures/GreyStation/Clothing/Head/Misc/tony.rsi/equipped-HELMET.png
  Resources/Textures/GreyStation/Clothing/Head/Misc/tony.rsi/icon.png
  Resources/Textures/GreyStation/Clothing/Head/Misc/tony.rsi/inhand-left.png
  Resources/Textures/GreyStation/Clothing/Head/Misc/tony.rsi/inhand-right.png
  Resources/Textures/GreyStation/Clothing/Head/Misc/tony.rsi/meta.json
  Resources/Textures/GreyStation/Objects/Weapons/Melee/bloody_knuckle_dusters.rsi/icon.png
  Resources/Textures/GreyStation/Objects/Weapons/Melee/bloody_knuckle_dusters.rsi/inhand-left.png
  Resources/Textures/GreyStation/Objects/Weapons/Melee/bloody_knuckle_dusters.rsi/inhand-right.png
  Resources/Textures/GreyStation/Objects/Weapons/Melee/bloody_knuckle_dusters.rsi/meta.json
  Resources/Textures/GreyStation/Objects/Weapons/Melee/bloody_knuckle_dusters.rsi/wielded-inhand-left.png
  Resources/Textures/GreyStation/Objects/Weapons/Melee/bloody_knuckle_dusters.rsi/wielded-inhand-right.png
Labels: No C#, Changes: Sprites

#341 Remove Duplicate YAML from Speech Traits
  Resources/Locale/en-US/greystation/traits/traits.ftl
  Resources/Prototypes/GreyStation/Traits/speech.yml
Labels: No C#

#342 Merge Upstream 9.16.24
  Content.Client/Examine/ExamineSystem.cs
  Content.Server/Objectives/Systems/StealConditionSystem.cs
  Content.Shared/Objectives/Prototypes/StealTargetGroupPrototype.cs
  Resources/Audio/Items/Toys/attributions.yml
  Resources/Audio/Items/Toys/rubber_chicken_1.ogg
  Resources/Audio/Items/Toys/rubber_chicken_2.ogg
  Resources/Audio/Items/Toys/rubber_chicken_3.ogg
  Resources/Changelog/Changelog.yml
  Resources/Locale/en-US/advertisements/vending/bruiseomat.ftl
  Resources/Locale/en-US/objectives/conditions/steal-target-groups.ftl
  Resources/Locale/en-US/objectives/conditions/steal.ftl
  Resources/Maps/Nonstations/nukieplanet.yml
  Resources/Prototypes/Catalog/Fills/Crates/fun.yml
  Resources/Prototypes/Catalog/VendingMachines/advertisements.yml
  Resources/Prototypes/Catalog/VendingMachines/goodbyes.yml
  Resources/Prototypes/Catalog/uplink_catalog.yml
  Resources/Prototypes/Entities/Markers/Spawners/Random/maintenance.yml
  Resources/Prototypes/Entities/Objects/Consumable/Food/snacks.yml
  Resources/Prototypes/Entities/Objects/Devices/encryption_keys.yml
  Resources/Prototypes/Entities/Objects/Fun/immovable_rod.yml
  Resources/Prototypes/Entities/Objects/Fun/toys.yml
  Resources/Prototypes/Entities/Structures/Doors/Airlocks/access.yml
  Resources/Prototypes/Entities/Structures/Machines/vending_machines.yml
  Resources/Prototypes/GameRules/meteorswarms.yml
  Resources/Prototypes/Hydroponics/randomMutations.yml
  Resources/Prototypes/Objectives/stealTargetGroups.yml
  Resources/Prototypes/Reagents/toxins.yml
  Resources/Prototypes/SoundCollections/rubber_chicken.yml
  Resources/Textures/Objects/Devices/encryption_keys.rsi/borg_label.png
  Resources/Textures/Objects/Devices/encryption_keys.rsi/meta.json
  Resources/Textures/Objects/Fun/toys.rsi/meta.json
  Resources/Textures/Objects/Fun/toys.rsi/rubber_chicken.png
  Resources/Textures/Structures/Machines/VendingMachines/bruiseomat.rsi/broken.png
  Resources/Textures/Structures/Machines/VendingMachines/bruiseomat.rsi/deny-unshaded.png
  Resources/Textures/Structures/Machines/VendingMachines/bruiseomat.rsi/meta.json
  Resources/Textures/Structures/Machines/VendingMachines/bruiseomat.rsi/normal-unshaded.png
  Resources/Textures/Structures/Machines/VendingMachines/bruiseomat.rsi/off.png
  Resources/Textures/Structures/Machines/VendingMachines/bruiseomat.rsi/panel.png
Labels: Changes: Sprites, Changes: Map

#343 Localize X-01 Steal Goal
  Resources/Audio/DeltaV/Weapons/Guns/Empty/dry_fire.ogg
  Resources/Audio/DeltaV/Weapons/Guns/Gunshots/laser.ogg
  Resources/Audio/DeltaV/license.txt
  Resources/Audio/GreyStation/Weapons/Guns/Gunshots/laser.ogg
  Resources/Audio/GreyStation/license.txt
  Resources/Locale/en-US/greystation/objectives/conditions/steal-target-groups.ftl
  Resources/Prototypes/DeltaV/Objectives/stealTargetGroups.yml
  Resources/Prototypes/GreyStation/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
  Resources/Prototypes/GreyStation/Entities/Objects/Weapons/Guns/Projectiles/impacts.yml
  Resources/Prototypes/GreyStation/Entities/Objects/Weapons/Guns/Shotguns/shotguns.yml
  Resources/Prototypes/GreyStation/Objectives/stealTargetGroups.yml
  Resources/Prototypes/GreyStation/Objectives/traitor.yml
  Resources/Textures/GreyStation/Objects/Weapons/Guns/Battery/energygun.rsi/base.png
  Resources/Textures/GreyStation/Objects/Weapons/Guns/Battery/energygun.rsi/disabler-inhand-left.png
  Resources/Textures/GreyStation/Objects/Weapons/Guns/Battery/energygun.rsi/disabler-inhand-right.png
  Resources/Textures/GreyStation/Objects/Weapons/Guns/Battery/energygun.rsi/icon.png
  Resources/Textures/GreyStation/Objects/Weapons/Guns/Battery/energygun.rsi/lethal-inhand-left.png
  Resources/Textures/GreyStation/Objects/Weapons/Guns/Battery/energygun.rsi/lethal-inhand-right.png
  Resources/Textures/GreyStation/Objects/Weapons/Guns/Battery/energygun.rsi/mag-unshaded-0.png
  Resources/Textures/GreyStation/Objects/Weapons/Guns/Battery/energygun.rsi/mag-unshaded-1.png
  Resources/Textures/GreyStation/Objects/Weapons/Guns/Battery/energygun.rsi/mag-unshaded-2.png
  Resources/Textures/GreyStation/Objects/Weapons/Guns/Battery/energygun.rsi/mag-unshaded-3.png
  Resources/Textures/GreyStation/Objects/Weapons/Guns/Battery/energygun.rsi/mag-unshaded-4.png
  Resources/Textures/GreyStation/Objects/Weapons/Guns/Battery/energygun.rsi/meta.json
  Resources/Textures/GreyStation/Objects/Weapons/Guns/Battery/energygun.rsi/mode-disabler.png
  Resources/Textures/GreyStation/Objects/Weapons/Guns/Battery/energygun.rsi/mode-lethal.png
  Resources/Textures/GreyStation/Objects/Weapons/Guns/Battery/energygun.rsi/mode-stun.png
  Resources/Textures/GreyStation/Objects/Weapons/Guns/Battery/energygun.rsi/special-inhand-left.png
  Resources/Textures/GreyStation/Objects/Weapons/Guns/Battery/energygun.rsi/special-inhand-right.png
  Resources/Textures/GreyStation/Objects/Weapons/Guns/Battery/multiphase_energygun.rsi/base.png
  Resources/Textures/GreyStation/Objects/Weapons/Guns/Battery/multiphase_energygun.rsi/disabler-inhand-left.png
  Resources/Textures/GreyStation/Objects/Weapons/Guns/Battery/multiphase_energygun.rsi/disabler-inhand-right.png
  Resources/Textures/GreyStation/Objects/Weapons/Guns/Battery/multiphase_energygun.rsi/equipped-BELT.png
  Resources/Textures/GreyStation/Objects/Weapons/Guns/Battery/multiphase_energygun.rsi/icon.png
  Resources/Textures/GreyStation/Objects/Weapons/Guns/Battery/multiphase_energygun.rsi/lethal-inhand-left.png
  Resources/Textures/GreyStation/Objects/Weapons/Guns/Battery/multiphase_energygun.rsi/lethal-inhand-right.png
  Resources/Textures/GreyStation/Objects/Weapons/Guns/Battery/multiphase_energygun.rsi/mag-unshaded-0.png
  Resources/Textures/GreyStation/Objects/Weapons/Guns/Battery/multiphase_energygun.rsi/mag-unshaded-1.png
  Resources/Textures/GreyStation/Objects/Weapons/Guns/Battery/multiphase_energygun.rsi/mag-unshaded-2.png
  Resources/Textures/GreyStation/Objects/Weapons/Guns/Battery/multiphase_energygun.rsi/mag-unshaded-3.png
  Resources/Textures/GreyStation/Objects/Weapons/Guns/Battery/multiphase_energygun.rsi/mag-unshaded-4.png
  Resources/Textures/GreyStation/Objects/Weapons/Guns/Battery/multiphase_energygun.rsi/meta.json
  Resources/Textures/GreyStation/Objects/Weapons/Guns/Battery/multiphase_energygun.rsi/mode-disabler.png
  Resources/Textures/GreyStation/Objects/Weapons/Guns/Battery/multiphase_energygun.rsi/mode-ion.png
  Resources/Textures/GreyStation/Objects/Weapons/Guns/Battery/multiphase_energygun.rsi/mode-lethal.png
  Resources/Textures/GreyStation/Objects/Weapons/Guns/Battery/multiphase_energygun.rsi/special-inhand-left.png
  Resources/Textures/GreyStation/Objects/Weapons/Guns/Battery/multiphase_energygun.rsi/special-inhand-right.png
Labels: No C#, Changes: Sprites

#345 Replace nospawn with categories: [ HideSpawnMenu ]
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml
  Resources/Prototypes/GreyStation/Actions/hailer.yml
  Resources/Prototypes/GreyStation/Catalog/Fills/Backpacks/StarterGear/dufflebag.yml
  Resources/Prototypes/GreyStation/Entities/Objects/Weapons/Guns/Projectiles/impacts.yml
  Resources/Prototypes/GreyStation/Objectives/traitor.yml
  Resources/Prototypes/Nyanotrasen/Entities/Objects/Consumable/Food/ration.yml
Labels: No C#

#338 Infestation Event Creature Changes
  Resources/Locale/en-US/greystation/interaction/interaction-popup-component.ftl
  Resources/Prototypes/GameRules/events.yml
  Resources/Prototypes/GreyStation/Entities/Mobs/NPCs/animals.yml
  Resources/Prototypes/GreyStation/GameRules/events.yml
Labels: No C#, Changes: Sprites

#348 Update Puddles Sprites
  Resources/Textures/Fluids/puddle.rsi/meta.json
  Resources/Textures/Fluids/puddle.rsi/splat0.png
  Resources/Textures/Fluids/puddle.rsi/splat1.png
  Resources/Textures/Fluids/puddle.rsi/splat10.png
  Resources/Textures/Fluids/puddle.rsi/splat11.png
  Resources/Textures/Fluids/puddle.rsi/splat12.png
  Resources/Textures/Fluids/puddle.rsi/splat13.png
  Resources/Textures/Fluids/puddle.rsi/splat14.png
  Resources/Textures/Fluids/puddle.rsi/splat15.png
  Resources/Textures/Fluids/puddle.rsi/splat2.png
  Resources/Textures/Fluids/puddle.rsi/splat3.png
  Resources/Textures/Fluids/puddle.rsi/splat4.png
  Resources/Textures/Fluids/puddle.rsi/splat5.png
  Resources/Textures/Fluids/puddle.rsi/splat6.png
  Resources/Textures/Fluids/puddle.rsi/splat7.png
  Resources/Textures/Fluids/puddle.rsi/splat8.png
  Resources/Textures/Fluids/puddle.rsi/splat9.png
  Resources/Textures/Fluids/puddle.rsi/splata.png
  Resources/Textures/Fluids/puddle.rsi/splatb.png
Labels: No C#, Changes: Sprites

#349 Added Scientist, Mullet, Brows n Stache Hair Options
  Resources/Locale/en-US/greystation/accessories/human-facial-hair.ftl
  Resources/Locale/en-US/greystation/accessories/human-hair.ftl
  Resources/Locale/en-US/greystation/traits/traits.ftl
  Resources/Prototypes/GreyStation/Entities/Mobs/Customization/Markings/human_facial_hair.yml
  Resources/Prototypes/GreyStation/Entities/Mobs/Customization/Markings/human_hair.yml
  Resources/Textures/GreyStation/Mobs/Customization/human_facial_hair.rsi/browsnstache.png
  Resources/Textures/GreyStation/Mobs/Customization/human_facial_hair.rsi/meta.json
  Resources/Textures/GreyStation/Mobs/Customization/human_hair.rsi/meta.json
  Resources/Textures/GreyStation/Mobs/Customization/human_hair.rsi/mullet.png
  Resources/Textures/GreyStation/Mobs/Customization/human_hair.rsi/scientist.png
Labels: No C#, Changes: Sprites

#350 Merge Upstream 9.23.24
  Content.Client/VendingMachines/VendingMachineBoundUserInterface.cs
  Content.Client/VendingMachines/VendingMachineSystem.cs
  Content.Client/Verbs/VerbSystem.cs
  Content.IntegrationTests/Tests/Construction/Interaction/ComputerContruction.cs
  Content.Server/VendingMachines/VendingMachineSystem.cs
  Content.Shared/CCVar/CCVars.cs
  Content.Shared/VendingMachines/SharedVendingMachineSystem.cs
  Content.Shared/VendingMachines/VendingMachineComponent.cs
  Content.Shared/VendingMachines/VendingMachineInterfaceState.cs
  Resources/Changelog/Admin.yml
  Resources/Changelog/Changelog.yml
  Resources/Locale/en-US/wires/wire-names.ftl
  Resources/Maps/Shuttles/ShuttleEvent/instigator.yml
  Resources/Prototypes/Entities/Objects/Misc/books.yml
  Resources/Prototypes/Entities/Objects/Specific/Mech/mechs.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/LMGs/lmgs.yml
  Resources/Prototypes/Entities/Structures/Machines/Computers/base_structurecomputers.yml
  Resources/Prototypes/Entities/Structures/Machines/Computers/computers.yml
  Resources/Prototypes/Entities/Structures/Machines/vending_machines.yml
  Resources/Prototypes/GameRules/unknown_shuttles.yml
  Resources/Prototypes/Recipes/Construction/Graphs/machines/computer.yml
  Resources/Prototypes/Shuttles/shuttle_incoming_event.yml
  Resources/Prototypes/Wires/layouts.yml
  Resources/Textures/Objects/Weapons/Guns/LMGs/l6.rsi/equipped-SUITSTORAGE.png
  Resources/Textures/Objects/Weapons/Guns/LMGs/l6.rsi/meta.json
  Resources/Textures/Structures/Machines/computers.rsi/generic_panel_open.png
  Resources/Textures/Structures/Machines/computers.rsi/meta.json
Labels: Changes: Sprites, Changes: Map

#347 pitbull port from deltav
  Content.Server/GreyStation/NPC/HostileOnInteractFailComponent.cs
  Content.Server/GreyStation/NPC/HostileOnInteractFailSystem.cs
  Resources/Locale/en-US/greystation/interaction/interaction-popup-component.ftl
  Resources/Prototypes/DeltaV/Entities/Clothing/Uniforms/jumpskirts.yml
  Resources/Prototypes/DeltaV/Entities/Clothing/Uniforms/jumpsuits.yml
  Resources/Prototypes/DeltaV/ai_factions.yml
  Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
  Resources/Prototypes/Entities/Mobs/NPCs/pets.yml
  Resources/Prototypes/GreyStation/Catalog/Cargo/cargo_livestock.yml
  Resources/Prototypes/GreyStation/Catalog/Fills/Crates/npc.yml
  Resources/Prototypes/GreyStation/Datasets/Names/pitbull.yml
  Resources/Prototypes/GreyStation/Entities/Mobs/NPCs/dogs.yml
  Resources/Prototypes/GreyStation/GameRules/events.yml
  Resources/Prototypes/GreyStation/ai_factions.yml
  Resources/Prototypes/Nyanotrasen/Entities/Clothing/Uniforms/jumpsuits.yml
  Resources/Textures/Nyanotrasen/Mobs/Pets/pitbull.rsi/alive.png
  Resources/Textures/Nyanotrasen/Mobs/Pets/pitbull.rsi/dead.png
  Resources/Textures/Nyanotrasen/Mobs/Pets/pitbull.rsi/meta.json
  Resources/Textures/Nyanotrasen/Mobs/Pets/ventbull.rsi/alive.png
  Resources/Textures/Nyanotrasen/Mobs/Pets/ventbull.rsi/dead.png
  Resources/Textures/Nyanotrasen/Mobs/Pets/ventbull.rsi/meta.json
Labels: Changes: Sprites

#352 Merge Upstream 9.24.24
  Content.Client/Paper/UI/PaperBoundUserInterface.cs
  Content.Client/Paper/UI/PaperWindow.xaml
  Content.Client/Paper/UI/PaperWindow.xaml.cs
  Content.Server/Chat/Systems/ChatSystem.cs
  Content.Shared/Paper/PaperSystem.cs
  Content.Shared/Storage/EntitySystems/SharedStorageSystem.cs
  Resources/Changelog/Changelog.yml
  Resources/Locale/en-US/paper/paper-component.ftl
  Resources/Maps/omega.yml
  Resources/Prototypes/Entities/Objects/Devices/pda.yml
  Resources/Prototypes/Roles/Jobs/Cargo/quartermaster.yml
  Resources/Prototypes/Roles/Jobs/Command/captain.yml
  Resources/Prototypes/Roles/Jobs/Command/head_of_personnel.yml
  Resources/Prototypes/Roles/Jobs/Engineering/chief_engineer.yml
  Resources/Prototypes/Roles/Jobs/Medical/chief_medical_officer.yml
  Resources/Prototypes/Roles/Jobs/Science/research_director.yml
  Resources/Prototypes/Roles/Jobs/Security/head_of_security.yml
Labels: Changes: Map, Changes: UI

#353 Resprite Conveyor Belts
  Resources/Prototypes/Entities/Structures/conveyor.yml
  Resources/Prototypes/Recipes/Construction/Graphs/structures/conveyor.yml
  Resources/Textures/GreyStation/Structures/conveyor.rsi/conveyor_loose.png
  Resources/Textures/GreyStation/Structures/conveyor.rsi/conveyor_started_ccw.png
  Resources/Textures/GreyStation/Structures/conveyor.rsi/conveyor_started_ccw_r.png
  Resources/Textures/GreyStation/Structures/conveyor.rsi/conveyor_started_cw.png
  Resources/Textures/GreyStation/Structures/conveyor.rsi/conveyor_started_cw_r.png
  Resources/Textures/GreyStation/Structures/conveyor.rsi/conveyor_stopped_ccw.png
  Resources/Textures/GreyStation/Structures/conveyor.rsi/conveyor_stopped_cw.png
  Resources/Textures/GreyStation/Structures/conveyor.rsi/greenlight.png
  Resources/Textures/GreyStation/Structures/conveyor.rsi/meta.json
  Resources/Textures/GreyStation/Structures/conveyor.rsi/redlight.png
  Resources/Textures/GreyStation/Structures/conveyor.rsi/switch-fwd.png
  Resources/Textures/GreyStation/Structures/conveyor.rsi/switch-off.png
  Resources/Textures/GreyStation/Structures/conveyor.rsi/switch-rev.png
  Resources/Textures/GreyStation/Structures/conveyor.rsi/switch.png
Labels: No C#, Changes: Sprites

#354 Merge Upstream 9.27.24
  Content.Client/Ensnaring/EnsnareableSystem.cs
  Content.Client/Inventory/StrippableBoundUserInterface.cs
  Content.Client/Popups/PopupSystem.cs
  Content.Client/Silicons/StationAi/StationAiSystem.Airlock.cs
  Content.Server/Administration/Systems/AdminVerbSystem.Tools.cs
  Content.Server/Construction/Completions/AttemptElectrocute.cs
  Content.Server/Doors/WireActions/DoorBoltWireAction.cs
  Content.Server/Electrocution/Components/ElectrifiedComponent.cs
  Content.Server/Electrocution/ElectrocutionSystem.cs
  Content.Server/Ensnaring/EnsnareableSystem.Ensnaring.cs
  Content.Server/Ensnaring/EnsnareableSystem.cs
  Content.Server/Power/PowerWireAction.cs
  Content.Server/Remotes/DoorRemoteSystem.cs
  Content.Server/Strip/StrippableSystem.cs
  Content.Shared/Doors/Components/AirlockComponent.cs
  Content.Shared/Doors/Systems/SharedAirlockSystem.cs
  Content.Shared/Doors/Systems/SharedDoorSystem.Bolts.cs
  Content.Shared/Doors/Systems/SharedDoorSystem.cs
  Content.Shared/Electrocution/Components/ElectrifiedComponent.cs
  Content.Shared/Electrocution/SharedElectrocutionSystem.cs
  Content.Shared/Ensnaring/Components/EnsnareableComponent.cs
  Content.Shared/Ensnaring/Components/EnsnaringComponent.cs
  Content.Shared/Ensnaring/SharedEnsnareableSystem.cs
  Content.Shared/Inventory/InventorySystem.Equip.cs
  Content.Shared/Power/EntitySystems/SharedPowerReceiverSystem.cs
  Content.Shared/Silicons/StationAi/SharedStationAiSystem.Airlock.cs
  Content.Shared/Silicons/StationAi/SharedStationAiSystem.Held.cs
  Content.Shared/Silicons/StationAi/SharedStationAiSystem.cs
  Content.Shared/Storage/EntitySystems/SharedStorageSystem.cs
  Content.Shared/Strip/SharedStrippableSystem.cs
  Resources/Audio/Machines/airlock_electrify_off.ogg
  Resources/Audio/Machines/airlock_electrify_on.ogg
  Resources/Audio/Machines/airlock_emergencyoff.ogg
  Resources/Audio/Machines/airlock_emergencyon.ogg
  Resources/Audio/Machines/attributions.yml
  Resources/Changelog/Changelog.yml
  Resources/Locale/en-US/ensnare/ensnare-component.ftl
  Resources/Locale/en-US/silicons/station-ai.ftl
  Resources/Prototypes/Entities/Objects/Fun/figurines.yml
  Resources/Prototypes/Entities/Structures/Piping/Atmospherics/binary.yml
  Resources/Prototypes/Loadouts/Jobs/Security/detective.yml
  Resources/Prototypes/Loadouts/loadout_groups.yml
  Resources/Prototypes/Objectives/objectiveGroups.yml
  Resources/Prototypes/Objectives/stealTargetGroups.yml
  Resources/Prototypes/Objectives/thief.yml
  Resources/Textures/Interface/Actions/actions_ai.rsi/bolt_door.png
  Resources/Textures/Interface/Actions/actions_ai.rsi/door_overcharge_off.png
  Resources/Textures/Interface/Actions/actions_ai.rsi/door_overcharge_on.png
  Resources/Textures/Interface/Actions/actions_ai.rsi/emergency_off.png
  Resources/Textures/Interface/Actions/actions_ai.rsi/emergency_on.png
  Resources/Textures/Interface/Actions/actions_ai.rsi/meta.json
  Resources/Textures/Interface/Actions/actions_ai.rsi/unbolt_door.png
Labels: Changes: Sprites, Changes: Map

#355 Fix typo
  Resources/Prototypes/GreyStation/GameRules/events.yml
Labels: No C#
