Repository greystation14/GreyStation14, pull requests merged in 2024-07, with the labels that each got.

#237 lobby art + icon changes
  Resources/Prototypes/lobbyscreens.yml
  Resources/Textures/LobbyScreens/attributions.yml
  Resources/Textures/LobbyScreens/blueprint.webp
  Resources/Textures/LobbyScreens/blueprint.webp.yml
  Resources/Textures/LobbyScreens/doomed.webp
  Resources/Textures/LobbyScreens/doomed.webp.yml
  Resources/Textures/LobbyScreens/greystation.png
  Resources/Textures/LobbyScreens/justaweekaway.webp.yml
  Resources/Textures/LobbyScreens/lobbyscreen1.png
  Resources/Textures/LobbyScreens/lobbyscreen2.png
  Resources/Textures/LobbyScreens/lobbyscreen3.png
  Resources/Textures/LobbyScreens/reclaimer-nuke.webp
  Resources/Textures/LobbyScreens/reclaimer-nuke.webp.yml
  Resources/Textures/Logo/icon/icon-32x32.png
Labels: No C#

#239 Fix Nyanotrasen Bar Signs
  Resources/Prototypes/Nyanotrasen/Entities/Structures/Wallmounts/Signs/bar_signs.yml
Labels: No C#

#245 Swat Mask Parents Sec Mask + Explorer Mask stats
  Resources/Prototypes/Entities/Clothing/Masks/masks.yml
Labels: No C#

#244 Remove Some ParkStation Benches
  Resources/Prototypes/SimpleStation14/benches.yml
  Resources/Textures/SimpleStation14/Structures/Furniture/Benches/parkbench_bamboo.rsi/left.png
  Resources/Textures/SimpleStation14/Structures/Furniture/Benches/parkbench_bamboo.rsi/meta.json
  Resources/Textures/SimpleStation14/Structures/Furniture/Benches/parkbench_bamboo.rsi/middle.png
  Resources/Textures/SimpleStation14/Structures/Furniture/Benches/parkbench_bamboo.rsi/right.png
  Resources/Textures/SimpleStation14/Structures/Furniture/Benches/parkbench_wooden.rsi/left.png
  Resources/Textures/SimpleStation14/Structures/Furniture/Benches/parkbench_wooden.rsi/meta.json
  Resources/Textures/SimpleStation14/Structures/Furniture/Benches/parkbench_wooden.rsi/middle.png
  Resources/Textures/SimpleStation14/Structures/Furniture/Benches/parkbench_wooden.rsi/right.png
  Resources/Textures/SimpleStation14/Structures/Furniture/Benches/pews.rsi/arm_left.png
  Resources/Textures/SimpleStation14/Structures/Furniture/Benches/pews.rsi/arm_right.png
  Resources/Textures/SimpleStation14/Structures/Furniture/Benches/pews.rsi/left.png
  Resources/Textures/SimpleStation14/Structures/Furniture/Benches/pews.rsi/meta.json
  Resources/Textures/SimpleStation14/Structures/Furniture/Benches/pews.rsi/middle.png
  Resources/Textures/SimpleStation14/Structures/Furniture/Benches/pews.rsi/right.png
  Resources/Textures/SimpleStation14/Structures/Furniture/Benches/sofa_corp.rsi/arm_left.png
  Resources/Textures/SimpleStation14/Structures/Furniture/Benches/sofa_corp.rsi/arm_right.png
  Resources/Textures/SimpleStation14/Structures/Furniture/Benches/sofa_corp.rsi/corner.png
  Resources/Textures/SimpleStation14/Structures/Furniture/Benches/sofa_corp.rsi/left.png
  Resources/Textures/SimpleStation14/Structures/Furniture/Benches/sofa_corp.rsi/meta.json
  Resources/Textures/SimpleStation14/Structures/Furniture/Benches/sofa_corp.rsi/middle.png
  Resources/Textures/SimpleStation14/Structures/Furniture/Benches/sofa_corp.rsi/right.png
  Resources/Textures/SimpleStation14/Structures/Furniture/Benches/steel_bench.rsi/left.png
  Resources/Textures/SimpleStation14/Structures/Furniture/Benches/steel_bench.rsi/meta.json
  Resources/Textures/SimpleStation14/Structures/Furniture/Benches/steel_bench.rsi/middle.png
  Resources/Textures/SimpleStation14/Structures/Furniture/Benches/steel_bench.rsi/right.png
  Resources/Textures/SimpleStation14/Structures/Furniture/Benches/steel_bench_white.rsi/left.png
  Resources/Textures/SimpleStation14/Structures/Furniture/Benches/steel_bench_white.rsi/meta.json
  Resources/Textures/SimpleStation14/Structures/Furniture/Benches/steel_bench_white.rsi/middle.png
  Resources/Textures/SimpleStation14/Structures/Furniture/Benches/steel_bench_white.rsi/right.png
Labels: No C#, Changes: Sprites

#242 noir and tequila glasses
  Content.Client/GreyStation/Clothing/ShaderClothingComponent.cs
  Content.Client/GreyStation/Clothing/ShaderClothingOverlay.cs
  Content.Client/GreyStation/Clothing/ShaderClothingSystem.cs
  Content.Server/Entry/IgnoredComponents.cs
  Resources/Prototypes/Catalog/VendingMachines/Inventories/detdrobe.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/theater.yml
  Resources/Prototypes/GreyStation/Entities/Clothing/Eyes/glasses.yml
  Resources/Prototypes/GreyStation/Shaders/mexico.yml
  Resources/Textures/GreyStation/Clothing/Eyes/Glasses/tequila_glasses.rsi/equipped-EYES.png
  Resources/Textures/GreyStation/Clothing/Eyes/Glasses/tequila_glasses.rsi/icon.png
  Resources/Textures/GreyStation/Clothing/Eyes/Glasses/tequila_glasses.rsi/meta.json
  Resources/Textures/GreyStation/Shaders/mexico_fullscreen.swsl
  error.glsl
Labels: Changes: Sprites

#246 Update Restock Cost for Theater-Drobe
  Resources/Prototypes/Catalog/Cargo/cargo_vending.yml
  Resources/Prototypes/GreyStation/Entities/Clothing/Eyes/glasses.yml
Labels: No C#

#248 Temporarily Remove Vox Round Start
  Resources/Prototypes/Species/vox.yml
Labels: No C#

#253 Sec Enlist Poster
  Resources/Prototypes/GreyStation/Entities/Structures/Wallmounts/Signs/posters.yml
  Resources/Textures/GreyStation/Structures/Wallmounts/Posters/misc.rsi/meta.json
  Resources/Textures/GreyStation/Structures/Wallmounts/Posters/misc.rsi/secenlist.png
Labels: No C#, Changes: Sprites

#247 jabroni outfit functionality but good
  Content.Shared/GreyStation/Clothing/ComponentsWhenWornComponent.cs
  Content.Shared/GreyStation/Clothing/ComponentsWhenWornSystem.cs
  Content.Shared/GreyStation/Sound/SoundOnMeleeComponent.cs
  Content.Shared/GreyStation/Sound/SoundOnMeleeSystem.cs
  Resources/Audio/GreyStation/Effects/Gachi/gangingup.ogg
  Resources/Audio/GreyStation/Effects/Gachi/huhyoulikeembarassingme.ogg
  Resources/Audio/GreyStation/Effects/Gachi/huhyoulikethat.ogg
  Resources/Audio/GreyStation/Effects/Gachi/knockedhimout.ogg
  Resources/Audio/GreyStation/Effects/Gachi/loud_FUCKYOU.ogg
  Resources/Audio/GreyStation/Effects/Gachi/ohmyshoulder.ogg
  Resources/Audio/GreyStation/Effects/Gachi/pain6.ogg
  Resources/Audio/GreyStation/Effects/Gachi/van_fuckyou.ogg
  Resources/Prototypes/GreyStation/SoundCollections/gachi.yml
  Resources/Prototypes/Nyanotrasen/Entities/Clothing/Uniforms/costumes.yml
  Resources/Textures/GreyStation/Clothing/Uniforms/Costume/jabroni.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/GreyStation/Clothing/Uniforms/Costume/jabroni.rsi/icon.png
  Resources/Textures/GreyStation/Clothing/Uniforms/Costume/jabroni.rsi/meta.json
Labels: Changes: Sprites

#255 Revert Ore-Locater MKII
  Resources/Prototypes/Catalog/Cargo/cargo_vending.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/salvage.yml
  Resources/Prototypes/GreyStation/Entities/Objects/Specific/Salvage/ore_locator.yml
  Resources/Textures/GreyStation/Objects/Specific/Salvage/orelocator.rsi/equipped-BELT.png
  Resources/Textures/GreyStation/Objects/Specific/Salvage/orelocator.rsi/icon.png
  Resources/Textures/GreyStation/Objects/Specific/Salvage/orelocator.rsi/inhand-left.png
  Resources/Textures/GreyStation/Objects/Specific/Salvage/orelocator.rsi/inhand-right.png
  Resources/Textures/GreyStation/Objects/Specific/Salvage/orelocator.rsi/meta.json
  Resources/Textures/GreyStation/Objects/Specific/Salvage/orelocator.rsi/screen.png
Labels: No C#, Changes: Sprites

#254 Update Jabroni Localization + Vending Machine tweaks
  Resources/Prototypes/Catalog/Cargo/cargo_vending.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/theater.yml
  Resources/Prototypes/GreyStation/Entities/Clothing/Uniforms/misc.yml
  Resources/Prototypes/Nyanotrasen/Entities/Clothing/Uniforms/costumes.yml
  Resources/Prototypes/Nyanotrasen/Inventories/boxingdrobe.yml
  Resources/Textures/Nyanotrasen/Clothing/Uniforms/Costume/jabroni.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/Nyanotrasen/Clothing/Uniforms/Costume/jabroni.rsi/icon.png
  Resources/Textures/Nyanotrasen/Clothing/Uniforms/Costume/jabroni.rsi/meta.json
Labels: No C#, Changes: Sprites

#257 add flippable quarter
  Content.Shared/GreyStation/Flipping/FlippableCoinComponent.cs
  Content.Shared/GreyStation/Flipping/FlippableCoinSystem.cs
  Content.Shared/GreyStation/Flipping/FlippingCoinComponent.cs
  Resources/Audio/GreyStation/Effects/attributions.yml
  Resources/Audio/GreyStation/Effects/coinflip.ogg
  Resources/Locale/en-US/greystation/coin-flip.ftl
  Resources/Prototypes/GreyStation/Entities/Objects/Misc/quarter.yml
  Resources/Textures/GreyStation/Objects/Misc/quarter.rsi/flipping_heads.png
  Resources/Textures/GreyStation/Objects/Misc/quarter.rsi/flipping_tails.png
  Resources/Textures/GreyStation/Objects/Misc/quarter.rsi/icon_heads.png
  Resources/Textures/GreyStation/Objects/Misc/quarter.rsi/icon_tails.png
  Resources/Textures/GreyStation/Objects/Misc/quarter.rsi/meta.json
Labels: Changes: Sprites

#258 Quarter Tweaks - Added to loadout trinkets + maintenance loot pile
  Resources/Prototypes/Entities/Markers/Spawners/Random/maintenance.yml
  Resources/Prototypes/GreyStation/Entities/Objects/Misc/quarter.yml
  Resources/Prototypes/Loadouts/Miscellaneous/trinkets.yml
  Resources/Prototypes/Loadouts/loadout_groups.yml
Labels: No C#

#259 Merge Upstream 7.13.24
  .github/workflows/publish.yml
  .github/workflows/test-packaging.yml
  Content.Client/Construction/ConstructionSystem.cs
  Content.Client/ContextMenu/UI/EntityMenuUIController.cs
  Content.Client/Gameplay/GameplayStateBase.cs
  Content.Client/Movement/Systems/JetpackSystem.cs
  Content.Client/NPC/PathfindingSystem.cs
  Content.Client/Physics/JointVisualsOverlay.cs
  Content.Client/Pinpointer/UI/NavMapControl.cs
  Content.Client/RCD/AlignRCDConstruction.cs
  Content.Client/Radiation/Overlays/RadiationPulseOverlay.cs
  Content.Client/Sandbox/SandboxSystem.cs
  Content.Client/Shuttles/Systems/ShuttleSystem.Console.cs
  Content.Client/Shuttles/UI/ShuttleMapControl.xaml.cs
  Content.Client/Storage/Systems/StorageSystem.cs
  Content.Client/Weapons/Melee/MeleeWeaponSystem.cs
  Content.Client/Weapons/Ranged/Systems/GunSystem.cs
  Content.Server/Atmos/EntitySystems/GasAnalyzerSystem.cs
  Content.Server/Dragon/DragonSystem.cs
  Content.Server/Guardian/GuardianSystem.cs
  Content.Server/Instruments/InstrumentSystem.cs
  Content.Server/Medical/HealthAnalyzerSystem.cs
  Content.Server/Movement/Systems/PullController.cs
  Content.Server/NPC/HTN/Preconditions/CoordinatesInRangePrecondition.cs
  Content.Server/NPC/HTN/Preconditions/CoordinatesNotInRangePrecondition.cs
  Content.Server/NPC/HTN/Preconditions/TargetInRangePrecondition.cs
  Content.Server/Pointing/EntitySystems/PointingSystem.cs
  Content.Shared/Access/Systems/IdExaminableSystem.cs
  Content.Shared/Actions/SharedActionsSystem.cs
  Content.Shared/DoAfter/SharedDoAfterSystem.Update.cs
  SpaceStation14.sln
  Tools/actions_changelog_rss.py
  Tools/gen_build_info.py
  Tools/publish_github_artifact.py
Labels: Changes: UI

#260 Remove Walking Solar Systems/Anomaly Core Rotating Ability
  Resources/Prototypes/Entities/Objects/Fun/toys.yml
  Resources/Prototypes/Entities/Structures/Specific/Anomaly/cores.yml
Labels: No C#

#261 Kendo Kit Crate at Cargo
  Resources/Audio/GreyStation/Effects/woodhit.ogg
  Resources/Prototypes/GreyStation/Catalog/Cargo/cargo_service.yml
  Resources/Prototypes/GreyStation/Catalog/Fills/Crates/service.yml
  Resources/Prototypes/Nyanotrasen/Entities/Objects/Weapons/Melee/blunt.yml
  Resources/Textures/Nyanotrasen/Objects/Weapons/Melee/shinai.rsi/icon.png
  Resources/Textures/Nyanotrasen/Objects/Weapons/Melee/shinai.rsi/inhand-left.png
  Resources/Textures/Nyanotrasen/Objects/Weapons/Melee/shinai.rsi/inhand-right.png
  Resources/Textures/Nyanotrasen/Objects/Weapons/Melee/shinai.rsi/meta.json
Labels: No C#, Changes: Sprites

#266 Fix Kendo Kit Price + Remove Female Mask Nyano Clothing
  Content.Shared/CCVar/CCVars.cs
  Resources/Prototypes/GreyStation/Catalog/Cargo/cargo_service.yml
  Resources/Prototypes/GreyStation/Catalog/Fills/Crates/service.yml
  Resources/Prototypes/Nyanotrasen/Entities/Clothing/Head/hats.yml
  Resources/Prototypes/Nyanotrasen/Entities/Clothing/Head/helmets.yml
  Resources/Prototypes/Nyanotrasen/Entities/Clothing/Uniforms/costumes.yml
Labels: No C#

#262 Moved Air Alarms 8 pixels down
  Resources/Textures/Structures/Wallmounts/air_monitors.rsi/alarm0.png
  Resources/Textures/Structures/Wallmounts/air_monitors.rsi/alarm1.png
  Resources/Textures/Structures/Wallmounts/air_monitors.rsi/alarm2.png
  Resources/Textures/Structures/Wallmounts/air_monitors.rsi/alarm_b1.png
  Resources/Textures/Structures/Wallmounts/air_monitors.rsi/alarm_b2.png
  Resources/Textures/Structures/Wallmounts/air_monitors.rsi/alarm_bitem.png
  Resources/Textures/Structures/Wallmounts/air_monitors.rsi/alarmp.png
  Resources/Textures/Structures/Wallmounts/air_monitors.rsi/alarmx.png
Labels: No C#, Changes: Sprites

#272 Update publish_github_artifact.py
  Tools/publish_github_artifact.py
Labels: No C#

#274 Sec Hardsuits Resprite
  Resources/Prototypes/Entities/Clothing/Head/hardsuit-helmets.yml
  Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
  Resources/Textures/GreyStation/Clothing/Head/Hardsuits/security-red.rsi/equipped-head-unshaded-vox.png
  Resources/Textures/GreyStation/Clothing/Head/Hardsuits/security-red.rsi/equipped-head-unshaded.png
  Resources/Textures/GreyStation/Clothing/Head/Hardsuits/security-red.rsi/icon-flash.png
  Resources/Textures/GreyStation/Clothing/Head/Hardsuits/security-red.rsi/icon.png
  Resources/Textures/GreyStation/Clothing/Head/Hardsuits/security-red.rsi/meta.json
  Resources/Textures/GreyStation/Clothing/Head/Hardsuits/security-red.rsi/off-equipped-HELMET-vox.png
  Resources/Textures/GreyStation/Clothing/Head/Hardsuits/security-red.rsi/off-equipped-HELMET.png
  Resources/Textures/GreyStation/Clothing/Head/Hardsuits/security-red.rsi/on-equipped-HELMET-vox.png
  Resources/Textures/GreyStation/Clothing/Head/Hardsuits/security-red.rsi/on-equipped-HELMET.png
  Resources/Textures/GreyStation/Clothing/Head/Hardsuits/security-warden.rsi/equipped-head-unshaded-vox.png
  Resources/Textures/GreyStation/Clothing/Head/Hardsuits/security-warden.rsi/equipped-head-unshaded.png
  Resources/Textures/GreyStation/Clothing/Head/Hardsuits/security-warden.rsi/icon-flash.png
  Resources/Textures/GreyStation/Clothing/Head/Hardsuits/security-warden.rsi/icon.png
  Resources/Textures/GreyStation/Clothing/Head/Hardsuits/security-warden.rsi/meta.json
  Resources/Textures/GreyStation/Clothing/Head/Hardsuits/security-warden.rsi/off-equipped-HELMET-vox.png
  Resources/Textures/GreyStation/Clothing/Head/Hardsuits/security-warden.rsi/off-equipped-HELMET.png
  Resources/Textures/GreyStation/Clothing/Head/Hardsuits/security-warden.rsi/on-equipped-HELMET-vox.png
  Resources/Textures/GreyStation/Clothing/Head/Hardsuits/security-warden.rsi/on-equipped-HELMET.png
  Resources/Textures/GreyStation/Clothing/Head/Hardsuits/security.rsi/equipped-head-unshaded-vox.png
  Resources/Textures/GreyStation/Clothing/Head/Hardsuits/security.rsi/equipped-head-unshaded.png
  Resources/Textures/GreyStation/Clothing/Head/Hardsuits/security.rsi/icon-flash.png
  Resources/Textures/GreyStation/Clothing/Head/Hardsuits/security.rsi/icon.png
  Resources/Textures/GreyStation/Clothing/Head/Hardsuits/security.rsi/meta.json
  Resources/Textures/GreyStation/Clothing/Head/Hardsuits/security.rsi/off-equipped-HELMET-vox.png
  Resources/Textures/GreyStation/Clothing/Head/Hardsuits/security.rsi/off-equipped-HELMET.png
  Resources/Textures/GreyStation/Clothing/Head/Hardsuits/security.rsi/on-equipped-HELMET-vox.png
  Resources/Textures/GreyStation/Clothing/Head/Hardsuits/security.rsi/on-equipped-HELMET.png
  Resources/Textures/GreyStation/Clothing/OuterClothing/Hardsuits/security-red.rsi/equipped-OUTERCLOTHING-vox.png
  Resources/Textures/GreyStation/Clothing/OuterClothing/Hardsuits/security-red.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/GreyStation/Clothing/OuterClothing/Hardsuits/security-red.rsi/icon.png
  Resources/Textures/GreyStation/Clothing/OuterClothing/Hardsuits/security-red.rsi/inhand-left.png
  Resources/Textures/GreyStation/Clothing/OuterClothing/Hardsuits/security-red.rsi/inhand-right.png
  Resources/Textures/GreyStation/Clothing/OuterClothing/Hardsuits/security-red.rsi/meta.json
  Resources/Textures/GreyStation/Clothing/OuterClothing/Hardsuits/security-warden.rsi/equipped-OUTERCLOTHING-vox.png
  Resources/Textures/GreyStation/Clothing/OuterClothing/Hardsuits/security-warden.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/GreyStation/Clothing/OuterClothing/Hardsuits/security-warden.rsi/icon.png
  Resources/Textures/GreyStation/Clothing/OuterClothing/Hardsuits/security-warden.rsi/inhand-left.png
  Resources/Textures/GreyStation/Clothing/OuterClothing/Hardsuits/security-warden.rsi/inhand-right.png
  Resources/Textures/GreyStation/Clothing/OuterClothing/Hardsuits/security-warden.rsi/meta.json
  Resources/Textures/GreyStation/Clothing/OuterClothing/Hardsuits/security.rsi/equipped-OUTERCLOTHING-vox.png
  Resources/Textures/GreyStation/Clothing/OuterClothing/Hardsuits/security.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/GreyStation/Clothing/OuterClothing/Hardsuits/security.rsi/icon.png
  Resources/Textures/GreyStation/Clothing/OuterClothing/Hardsuits/security.rsi/inhand-left.png
  Resources/Textures/GreyStation/Clothing/OuterClothing/Hardsuits/security.rsi/inhand-right.png
  Resources/Textures/GreyStation/Clothing/OuterClothing/Hardsuits/security.rsi/meta.json
Labels: No C#, Changes: Sprites

#276 remove option for modern ui layout
  Content.Client/Options/UI/Tabs/MiscTab.xaml.cs
  Content.Shared/CCVar/CCVars.cs
Labels: Changes: UI
