Repository greystation14/GreyStation14, pull requests merged in 2024-06, with the labels that each got.

#188 Fixing DeltaV Vending Machine
  Resources/Prototypes/DeltaV/Catalog/VendingMachines/Advertisements/pride.yml
  Resources/Prototypes/DeltaV/Catalog/VendingMachines/Goodbyes/pride.yml
  Resources/Prototypes/DeltaV/Catalog/VendingMachines/advertisements.yml
  Resources/Prototypes/DeltaV/Catalog/VendingMachines/goodbyes.yml
  Resources/Prototypes/GreyStation/Catalog/VendingMachines/Advertisements/spookydrobe.yml
  Resources/Prototypes/GreyStation/Catalog/VendingMachines/Goodbyes/spookydrobe.yml
  Resources/Prototypes/GreyStation/Catalog/VendingMachines/advertisements.yml
  Resources/Prototypes/GreyStation/Catalog/VendingMachines/goodbyes.yml
Labels: No C#

#190 Fix Upstream Merge 6.3.24
  Resources/Prototypes/DeltaV/Entities/Objects/Consumable/Food/Baked/pie.yml
  Resources/Prototypes/GreyStation/Entities/Mobs/NPCs/mutants.yml
  Resources/Prototypes/Nyanotrasen/Entities/Objects/Consumable/Food/Baked/pizza.yml
  Resources/Prototypes/Nyanotrasen/Entities/Objects/Weapons/Melee/breaching_hammer.yml
Labels: No C#

#172 sec gas mask hailer
  Content.Client/GreyStation/Hailer/HailerSystem.cs
  Content.Client/GreyStation/Hailer/UI/HailerBoundUserInterface.cs
  Content.Client/GreyStation/Hailer/UI/HailerRadialMenu.xaml
  Content.Client/GreyStation/Hailer/UI/HailerRadialMenu.xaml.cs
  Content.Server/GreyStation/Hailer/HailerSystem.cs
  Content.Shared/GreyStation/Hailer/HailerComponent.cs
  Content.Shared/GreyStation/Hailer/HailerUi.cs
  Content.Shared/GreyStation/Hailer/SharedHailerSystem.cs
  Resources/Audio/GreyStation/Hailer/Combat/asshole.ogg
  Resources/Audio/GreyStation/Hailer/Combat/attributions.yml
  Resources/Audio/GreyStation/Hailer/Combat/bash.ogg
  Resources/Audio/GreyStation/Hailer/Combat/dontmove.ogg
  Resources/Audio/GreyStation/Hailer/Combat/dredd.ogg
  Resources/Audio/GreyStation/Hailer/Combat/floor.ogg
  Resources/Audio/GreyStation/Hailer/Combat/freeze.ogg
  Resources/Audio/GreyStation/Hailer/Combat/harry.ogg
  Resources/Audio/GreyStation/Hailer/Combat/imperial.ogg
  Resources/Audio/GreyStation/Hailer/Combat/robocop.ogg
  Resources/Audio/GreyStation/Hailer/Combat/stfu.ogg
  Resources/Audio/GreyStation/Hailer/Emagged/attributions.yml
  Resources/Audio/GreyStation/Hailer/Emagged/binsult.ogg
  Resources/Audio/GreyStation/Hailer/Normal/attributions.yml
  Resources/Audio/GreyStation/Hailer/Normal/compliance.ogg
  Resources/Audio/GreyStation/Hailer/Normal/halt.ogg
  Resources/Audio/GreyStation/Hailer/Normal/justice.ogg
  Resources/Audio/GreyStation/Hailer/Normal/running.ogg
  Resources/Audio/GreyStation/Hailer/Normal/stop.ogg
  Resources/Locale/en-US/greystation/hailer.ftl
  Resources/Prototypes/Entities/Clothing/Masks/masks.yml
  Resources/Prototypes/GreyStation/Actions/hailer.yml
  Resources/Textures/GreyStation/Interface/Actions/hailer.rsi/meta.json
  Resources/Textures/GreyStation/Interface/Actions/hailer.rsi/picker.png
Labels: Changes: Sprites, Changes: Map, Changes: UI

#192 Return of the Urist Cloned Syndicate Agents
  Resources/Prototypes/Entities/Mobs/Player/human.yml
Labels: No C#

#194 Fixes Nyano Bags Bug
  Resources/Prototypes/Nyanotrasen/Roles/Jobs/Security/prisonguard.yml
  Resources/Prototypes/Nyanotrasen/Roles/Jobs/Wildcards/martialartist.yml
  Resources/Prototypes/Nyanotrasen/Roles/Jobs/Wildcards/prisoner.yml
Labels: No C#

#195 Decrease Texture Size for Sec Hailer Ability
  Resources/Textures/GreyStation/Interface/Actions/hailer.rsi/meta.json
  Resources/Textures/GreyStation/Interface/Actions/hailer.rsi/picker.png
Labels: No C#, Changes: Sprites

#197 Merge Fix 6.5.24
  Resources/Locale/en-US/deltav/flavors/flavor-profiles.ftl
  Resources/Locale/en-US/nyanotrasen/reagents/meta/consumable/drink/drink.ftl
Labels: No C#

#198 Update Trinkets
  Resources/Prototypes/Loadouts/Miscellaneous/trinkets.yml
  Resources/Prototypes/Loadouts/loadout_groups.yml
Labels: No C#

#201 Transfer Space Law and Server Rules
  Resources/Locale/en-US/greystation/guidebook/guides.ftl
  Resources/Locale/en-US/guidebook/guides.ftl
  Resources/Prototypes/GreyStation/Entities/Objects/Misc/books.yml
  Resources/Prototypes/GreyStation/Guidebook/spacelaw.yml
  Resources/Prototypes/Guidebook/rules.yml
  Resources/Prototypes/Guidebook/species.yml
  Resources/ServerInfo/GreyStation/Guidebook/SpaceLaw.xml
  Resources/ServerInfo/GreyStation/Guidebook/SpaceLaw/GeneralInfo.xml
  Resources/ServerInfo/GreyStation/Guidebook/SpaceLaw/SecurityPolicies.xml
  Resources/ServerInfo/GreyStation/Guidebook/SpaceLaw/SpaceLaw.xml
  Resources/ServerInfo/Guidebook/Mobs/Arachnid.xml
  Resources/ServerInfo/Guidebook/Mobs/Diona.xml
  Resources/ServerInfo/Guidebook/Mobs/Dwarf.xml
  Resources/ServerInfo/Guidebook/Mobs/Moth.xml
  Resources/ServerInfo/Guidebook/Mobs/Reptilian.xml
  Resources/ServerInfo/Guidebook/Mobs/SlimePerson.xml
  Resources/ServerInfo/Guidebook/Mobs/Species.xml
  Resources/ServerInfo/Guidebook/ServerRules/BanDurations.xml
  Resources/ServerInfo/Guidebook/ServerRules/BanTypes.xml
  Resources/ServerInfo/Guidebook/ServerRules/CoreRules/RuleC0.xml
  Resources/ServerInfo/Guidebook/ServerRules/CoreRules/RuleC12MinAge.xml
  Resources/ServerInfo/Guidebook/ServerRules/CoreRules/RuleC13CharacterNames.xml
  Resources/ServerInfo/Guidebook/ServerRules/CoreRules/RuleC14ICinOOC.xml
  Resources/ServerInfo/Guidebook/ServerRules/CoreRules/RuleC1Admins.xml
  Resources/ServerInfo/Guidebook/ServerRules/CoreRules/RuleC2DBAD.xml
  Resources/ServerInfo/Guidebook/ServerRules/CoreRules/RuleC3NoHate.xml
  Resources/ServerInfo/Guidebook/ServerRules/CoreRules/RuleC4NoERP.xml
  Resources/ServerInfo/Guidebook/ServerRules/CoreRules/RuleC6BanEvasion.xml
  Resources/ServerInfo/Guidebook/ServerRules/DefaultRules.xml
  Resources/ServerInfo/Guidebook/ServerRules/RoleplayRules/RuleR14SecComStandard.xml
  Resources/ServerInfo/Guidebook/ServerRules/SpaceLaw/SLCrimeList.xml
  Resources/ServerInfo/Guidebook/ServerRules/SpaceLaw/SLPrisonerProcessing.xml
  Resources/ServerInfo/Guidebook/ServerRules/SpaceLaw/SLRestrictedWeapons.xml
  Resources/ServerInfo/Guidebook/ServerRules/WizDenCoreOnlyRules.xml
  Resources/ServerInfo/Guidebook/ServerRules/WizDenLRPRules.xml
  Resources/ServerInfo/Guidebook/ServerRules/WizDenMRPRules.xml
Labels: No C#

#205 Merge Upstream 6.7.24
  Content.Client/Construction/UI/FlatpackCreatorMenu.xaml
  Content.Client/Construction/UI/FlatpackCreatorMenu.xaml.cs
  Content.Client/Guidebook/Controls/GuidebookWindow.xaml
  Content.Client/Guidebook/Controls/GuidebookWindow.xaml.cs
  Content.Client/UserInterface/Systems/Guidebook/GuidebookUIController.cs
  Content.Shared/Guidebook/GuideEntry.cs
  Resources/Changelog/Changelog.yml
  Resources/Locale/en-US/guidebook/guides.ftl
  Resources/Maps/core.yml
  Resources/Prototypes/Guidebook/rules.yml
  Resources/Prototypes/Guidebook/security.yml
  Resources/Prototypes/Guidebook/ss14.yml
  Resources/Prototypes/Recipes/Cooking/medical_recipes.yml
  Resources/ServerInfo/Guidebook/ServerRules/CoreRules/RuleC11AhelpThreats.xml
  Resources/ServerInfo/Guidebook/ServerRules/CoreRules/RuleC13CharacterNames.xml
  Resources/ServerInfo/Guidebook/ServerRules/RoleplayRules/RuleR11Escalation.xml
  Resources/ServerInfo/Guidebook/ServerRules/RoleplayRules/RuleR15SpaceLaw.xml
  Resources/ServerInfo/Guidebook/ServerRules/RoleplayRules/RuleR2Familiars.xml
  Resources/ServerInfo/Guidebook/ServerRules/RoleplayRules/RuleR4Metashield.xml
  Resources/ServerInfo/Guidebook/ServerRules/RoleplayRules/RuleR5Arrivals.xml
  Resources/ServerInfo/Guidebook/ServerRules/RoleplayRules/RuleR9MassSabotage.xml
  Resources/ServerInfo/Guidebook/ServerRules/SpaceLaw/SLCrimeList.xml
  Resources/ServerInfo/Guidebook/ServerRules/SpaceLaw/SLRestrictedWeapons.xml
  Resources/ServerInfo/Guidebook/ServerRules/SpaceLaw/SpaceLaw.xml
Labels: Changes: Map, Changes: UI

#206 Merge Upstream 6.8.24
  Content.Client/Construction/ConstructionSystem.cs
  Content.Client/Construction/UI/FlatpackCreatorMenu.xaml.cs
  Content.Client/Light/RgbLightControllerSystem.cs
  Content.Client/UserInterface/Systems/Actions/Controls/ActionButton.cs
  Content.Packaging/Program.cs
  Content.Server/Administration/Systems/AdminVerbSystem.cs
  Content.Server/Chat/Systems/ChatSystem.cs
  Content.Server/Construction/FlatpackSystem.cs
  Content.Server/Damage/Systems/DamageOtherOnHitSystem.cs
  Content.Server/Devour/DevourSystem.cs
  Content.Server/Explosion/EntitySystems/TriggerSystem.OnUse.cs
  Content.Server/Instruments/InstrumentSystem.cs
  Content.Server/ParticleAccelerator/EntitySystems/ParticleAcceleratorSystem.Emitter.cs
  Content.Server/Singularity/EntitySystems/SingularitySystem.cs
  Content.Shared/Construction/SharedFlatpackSystem.cs
  Content.Shared/Explosion/Components/OnUseTimerTriggerComponent.cs
  Content.Shared/Preferences/HumanoidCharacterProfile.cs
  Content.Shared/Preferences/Loadouts/RoleLoadout.cs
  Content.Shared/Singularity/Components/SingularityComponent.cs
  Resources/Changelog/Admin.yml
  Resources/Changelog/Changelog.yml
  Resources/Locale/en-US/interaction/interaction-popup-component.ftl
  Resources/Locale/en-US/speech/speech-chatsan.ftl
  Resources/Maps/core.yml
  Resources/Prototypes/Accents/word_replacements.yml
  Resources/Prototypes/Entities/Objects/Consumable/Drinks/drinks-cartons.yml
  Resources/Prototypes/Entities/Objects/Consumable/Drinks/drinks_bottles.yml
  Resources/ServerInfo/Guidebook/Engineering/Singularity.xml
Labels: Changes: Map, Changes: UI

#208 Remove wide swinging + ghost roles from certain animals and all slimes
  Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
  Resources/Prototypes/Entities/Mobs/NPCs/slimes.yml
Labels: No C#

#210 Update Bulletproof Armor Sprite
  Resources/Prototypes/Entities/Clothing/OuterClothing/armor.yml
  Resources/Textures/GreyStation/Clothing/OuterClothing/Armor/bulletproof.rsi/equipped-OUTERCLOTHING-vox.png
  Resources/Textures/GreyStation/Clothing/OuterClothing/Armor/bulletproof.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/GreyStation/Clothing/OuterClothing/Armor/bulletproof.rsi/icon.png
  Resources/Textures/GreyStation/Clothing/OuterClothing/Armor/bulletproof.rsi/inhand-left.png
  Resources/Textures/GreyStation/Clothing/OuterClothing/Armor/bulletproof.rsi/inhand-right.png
  Resources/Textures/GreyStation/Clothing/OuterClothing/Armor/bulletproof.rsi/meta.json
Labels: No C#, Changes: Sprites

#213 Resprite Outlaw hat
  Resources/Prototypes/Entities/Clothing/Head/hats.yml
  Resources/Textures/GreyStation/Clothing/Head/Hats/outlawhat.rsi/equipped-HELMET-hamster.png
  Resources/Textures/GreyStation/Clothing/Head/Hats/outlawhat.rsi/equipped-HELMET.png
  Resources/Textures/GreyStation/Clothing/Head/Hats/outlawhat.rsi/icon.png
  Resources/Textures/GreyStation/Clothing/Head/Hats/outlawhat.rsi/inhand-left.png
  Resources/Textures/GreyStation/Clothing/Head/Hats/outlawhat.rsi/inhand-right.png
  Resources/Textures/GreyStation/Clothing/Head/Hats/outlawhat.rsi/meta.json
Labels: No C#, Changes: Sprites

#216 We do a little trolling
  Resources/Prototypes/Catalog/Cargo/cargo_vending.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/theater.yml
  Resources/Prototypes/GreyStation/Entities/Clothing/Masks/masks.yml
  Resources/Textures/GreyStation/Clothing/Mask/troll.rsi/equipped-MASK.png
  Resources/Textures/GreyStation/Clothing/Mask/troll.rsi/icon.png
  Resources/Textures/GreyStation/Clothing/Mask/troll.rsi/inhand-left.png
  Resources/Textures/GreyStation/Clothing/Mask/troll.rsi/inhand-right.png
  Resources/Textures/GreyStation/Clothing/Mask/troll.rsi/meta.json
Labels: No C#, Changes: Sprites

#218 Merge Upstream 6.17.24
  Content.Client/Clothing/ClientClothingSystem.cs
  Content.Client/Clothing/FlippableClothingVisualizerSystem.cs
  Content.Client/Clothing/FlippableClothingVisualsComponent.cs
  Content.Client/Robotics/UI/RoboticsConsoleWindow.xaml.cs
  Content.Client/Sprite/RandomSpriteSystem.cs
  Content.Server/Explosion/Components/AutomatedTimerComponent.cs
  Content.Server/Explosion/EntitySystems/TriggerSystem.OnUse.cs
  Content.Server/Explosion/EntitySystems/TriggerSystem.cs
  Content.Server/Silicons/Borgs/BorgSystem.Transponder.cs
  Content.Server/Silicons/Borgs/BorgSystem.cs
  Content.Server/Speech/Components/AccentWearerNameClothingComponent.cs
  Content.Server/Speech/EntitySystems/AccentWearerNameClothingSystem.cs
  Content.Server/StationEvents/Events/MeteorSwarmSystem.cs
  Content.Shared/Clothing/Components/ClothingComponent.cs
  Content.Shared/Clothing/EntitySystems/ClothingSystem.cs
  Content.Shared/Clothing/EntitySystems/FoldableClothingSystem.cs
  Content.Shared/Robotics/Components/RoboticsConsoleComponent.cs
  Content.Shared/Robotics/RoboticsConsoleUi.cs
  Content.Shared/Silicons/Borgs/Components/BorgTransponderComponent.cs
  Resources/Changelog/Changelog.yml
  Resources/Locale/en-US/borg/borg.ftl
  Resources/Locale/en-US/markings/reptilian.ftl
  Resources/Locale/en-US/research/components/robotics-console.ftl
  Resources/Locale/en-US/speech/accent-wearer-name-clothing.ftl
  Resources/Maps/Shuttles/emergency_meta.yml
  Resources/Maps/atlas.yml
  Resources/Maps/bagel.yml
  Resources/Maps/cluster.yml
  Resources/Maps/marathon.yml
  Resources/Maps/oasis.yml
  Resources/Maps/saltern.yml
  Resources/Prototypes/Entities/Clothing/Eyes/base_clothingeyes.yml
  Resources/Prototypes/Entities/Clothing/Eyes/hud.yml
  Resources/Prototypes/Entities/Clothing/Eyes/misc.yml
  Resources/Prototypes/Entities/Clothing/Head/hats.yml
  Resources/Prototypes/Entities/Mobs/Customization/Markings/reptilian.yml
  Resources/Prototypes/Entities/Mobs/Cyborgs/base_borg_chassis.yml
  Resources/Textures/Mobs/Customization/reptilian_parts.rsi/horns_demonic.png
  Resources/Textures/Mobs/Customization/reptilian_parts.rsi/meta.json
Labels: Changes: Sprites, Changes: Map, Changes: UI

#219 Update + Fix Nukie Mouse and Vasquez
  Resources/Prototypes/DeltaV/Entities/Mobs/NPCs/nukiemouse.yml
  Resources/Prototypes/GreyStation/Entities/Mobs/NPCs/xeno.yml
Labels: No C#

#224 Fixed Most Sec Outfits
  Resources/Prototypes/Entities/Clothing/Head/hats.yml
  Resources/Prototypes/Entities/Clothing/Head/helmets.yml
  Resources/Prototypes/Entities/Clothing/Uniforms/jumpskirts.yml
  Resources/Prototypes/Entities/Clothing/Uniforms/jumpsuits.yml
  Resources/Prototypes/GreyStation/Entities/Clothing/Head/hats.yml
  Resources/Prototypes/Loadouts/Jobs/Security/head_of_security.yml
  Resources/Prototypes/Loadouts/loadout_groups.yml
  Resources/Textures/GreyStation/Clothing/Head/Helmets/security.rsi/equipped-HELMET-vox.png
  Resources/Textures/GreyStation/Clothing/Head/Helmets/security.rsi/equipped-HELMET.png
  Resources/Textures/GreyStation/Clothing/Head/Helmets/security.rsi/icon.png
  Resources/Textures/GreyStation/Clothing/Head/Helmets/security.rsi/inhand-left.png
  Resources/Textures/GreyStation/Clothing/Head/Helmets/security.rsi/inhand-right.png
  Resources/Textures/GreyStation/Clothing/Head/Helmets/security.rsi/light-equipped-HELMET.png
  Resources/Textures/GreyStation/Clothing/Head/Helmets/security.rsi/lighton-equipped-HELMET.png
  Resources/Textures/GreyStation/Clothing/Head/Helmets/security.rsi/meta.json
  Resources/Textures/GreyStation/Clothing/Uniforms/Jumpskirt/security.rsi/equipped-INNERCLOTHING-monkey.png
  Resources/Textures/GreyStation/Clothing/Uniforms/Jumpskirt/security.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/GreyStation/Clothing/Uniforms/Jumpskirt/security.rsi/icon.png
  Resources/Textures/GreyStation/Clothing/Uniforms/Jumpskirt/security.rsi/inhand-left.png
  Resources/Textures/GreyStation/Clothing/Uniforms/Jumpskirt/security.rsi/inhand-right.png
  Resources/Textures/GreyStation/Clothing/Uniforms/Jumpskirt/security.rsi/meta.json
  Resources/Textures/GreyStation/Clothing/Uniforms/Jumpskirt/warden.rsi/equipped-INNERCLOTHING-monkey.png
  Resources/Textures/GreyStation/Clothing/Uniforms/Jumpskirt/warden.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/GreyStation/Clothing/Uniforms/Jumpskirt/warden.rsi/icon.png
  Resources/Textures/GreyStation/Clothing/Uniforms/Jumpskirt/warden.rsi/inhand-left.png
  Resources/Textures/GreyStation/Clothing/Uniforms/Jumpskirt/warden.rsi/inhand-right.png
  Resources/Textures/GreyStation/Clothing/Uniforms/Jumpskirt/warden.rsi/meta.json
  Resources/Textures/GreyStation/Clothing/Uniforms/Jumpsuit/security.rsi/equipped-INNERCLOTHING-monkey.png
  Resources/Textures/GreyStation/Clothing/Uniforms/Jumpsuit/security.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/GreyStation/Clothing/Uniforms/Jumpsuit/security.rsi/icon.png
  Resources/Textures/GreyStation/Clothing/Uniforms/Jumpsuit/security.rsi/inhand-left.png
  Resources/Textures/GreyStation/Clothing/Uniforms/Jumpsuit/security.rsi/inhand-right.png
  Resources/Textures/GreyStation/Clothing/Uniforms/Jumpsuit/security.rsi/meta.json
  Resources/Textures/GreyStation/Clothing/Uniforms/Jumpsuit/warden.rsi/equipped-INNERCLOTHING-monkey.png
  Resources/Textures/GreyStation/Clothing/Uniforms/Jumpsuit/warden.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/GreyStation/Clothing/Uniforms/Jumpsuit/warden.rsi/icon.png
  Resources/Textures/GreyStation/Clothing/Uniforms/Jumpsuit/warden.rsi/inhand-left.png
  Resources/Textures/GreyStation/Clothing/Uniforms/Jumpsuit/warden.rsi/inhand-right.png
  Resources/Textures/GreyStation/Clothing/Uniforms/Jumpsuit/warden.rsi/meta.json
Labels: No C#, Changes: Sprites

#226 Fix Breaching Hammer + Initial Infected Exempt Error
  Resources/Prototypes/GreyStation/Entities/Mobs/Player/human.yml
  Resources/Prototypes/Nyanotrasen/Entities/Objects/Weapons/Melee/breaching_hammer.yml
Labels: No C#

#229 Added Space Cop Costume
  Resources/Prototypes/GreyStation/Entities/Clothing/Head/helmets.yml
  Resources/Prototypes/GreyStation/Entities/Clothing/OuterClothing/misc.yml
  Resources/Textures/GreyStation/Clothing/Head/Helmets/judgehelm.rsi/equipped-HELMET-hamster.png
  Resources/Textures/GreyStation/Clothing/Head/Helmets/judgehelm.rsi/equipped-HELMET.png
  Resources/Textures/GreyStation/Clothing/Head/Helmets/judgehelm.rsi/icon.png
  Resources/Textures/GreyStation/Clothing/Head/Helmets/judgehelm.rsi/inhand-left.png
  Resources/Textures/GreyStation/Clothing/Head/Helmets/judgehelm.rsi/inhand-right.png
  Resources/Textures/GreyStation/Clothing/Head/Helmets/judgehelm.rsi/meta.json
  Resources/Textures/GreyStation/Clothing/OuterClothing/Misc/dredd.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/GreyStation/Clothing/OuterClothing/Misc/dredd.rsi/icon.png
  Resources/Textures/GreyStation/Clothing/OuterClothing/Misc/dredd.rsi/inhand-left.png
  Resources/Textures/GreyStation/Clothing/OuterClothing/Misc/dredd.rsi/inhand-right.png
  Resources/Textures/GreyStation/Clothing/OuterClothing/Misc/dredd.rsi/meta.json
Labels: No C#, Changes: Sprites

#232 Bring back OG security webbing
  Resources/Prototypes/Entities/Clothing/Belt/belts.yml
  Resources/Textures/GreyStation/Clothing/Belt/securitywebbing.rsi/equipped-BELT.png
  Resources/Textures/GreyStation/Clothing/Belt/securitywebbing.rsi/icon.png
  Resources/Textures/GreyStation/Clothing/Belt/securitywebbing.rsi/inhand-left.png
  Resources/Textures/GreyStation/Clothing/Belt/securitywebbing.rsi/inhand-right.png
  Resources/Textures/GreyStation/Clothing/Belt/securitywebbing.rsi/meta.json
Labels: No C#, Changes: Sprites

#222 Reverts Upstream Sprite Changes to APC + Substation
  Content.Client/Power/APC/ApcVisualizerComponent.cs
  Resources/Prototypes/Entities/Structures/Power/apc.yml
  Resources/Prototypes/Entities/Structures/Power/substation.yml
  Resources/Textures/GreyStation/Structures/Power/apc.rsi/base.png
  Resources/Textures/GreyStation/Structures/Power/apc.rsi/broken.png
  Resources/Textures/GreyStation/Structures/Power/apc.rsi/display-charging.png
  Resources/Textures/GreyStation/Structures/Power/apc.rsi/display-full.png
  Resources/Textures/GreyStation/Structures/Power/apc.rsi/display-lack.png
  Resources/Textures/GreyStation/Structures/Power/apc.rsi/display-remote.png
  Resources/Textures/GreyStation/Structures/Power/apc.rsi/emag-unlit.png
  Resources/Textures/GreyStation/Structures/Power/apc.rsi/frame.png
  Resources/Textures/GreyStation/Structures/Power/apc.rsi/lock0-locked.png
  Resources/Textures/GreyStation/Structures/Power/apc.rsi/lock1-locked.png
  Resources/Textures/GreyStation/Structures/Power/apc.rsi/meta.json
  Resources/Textures/GreyStation/Structures/Power/apc.rsi/panel.png
  Resources/Textures/GreyStation/Structures/Power/apc.rsi/sparks-unlit.png
  Resources/Textures/GreyStation/Structures/Power/apc.rsi/static.png
  Resources/Textures/GreyStation/Structures/Power/substation.rsi/charging.png
  Resources/Textures/GreyStation/Structures/Power/substation.rsi/dead.png
  Resources/Textures/GreyStation/Structures/Power/substation.rsi/full.png
  Resources/Textures/GreyStation/Structures/Power/substation.rsi/meta.json
  Resources/Textures/GreyStation/Structures/Power/substation.rsi/screen.png
  Resources/Textures/GreyStation/Structures/Power/substation.rsi/substation.png
  Resources/Textures/GreyStation/Structures/Power/substation.rsi/substation_static.png
  Resources/Textures/GreyStation/Structures/Power/substation.rsi/substation_wall.png
  Resources/Textures/GreyStation/Structures/Power/substation.rsi/substation_wall_static.png
Labels: Changes: Sprites

#233 Upstream Merge 6.28.24
  Content.Client/Construction/UI/ConstructionMenu.xaml
  Content.Client/Construction/UI/ConstructionMenu.xaml.cs
  Content.Client/Construction/UI/ConstructionMenuPresenter.cs
  Content.Server/Atmos/Piping/Unary/Components/GasVentPumpComponent.cs
  Content.Server/Atmos/Piping/Unary/Components/GasVentScrubberComponent.cs
  Content.Server/Objectives/Components/StoreUnlockerComponent.cs
  Content.Server/Objectives/Systems/StoreUnlockerSystem.cs
  Content.Server/Store/Conditions/ObjectiveUnlockCondition.cs
  Content.Shared/Cabinet/ItemCabinetSystem.cs
  Content.Shared/Cabinet/SealingCabinetComponent.cs
  Content.Shared/Cabinet/SealingCabinetSystem.cs
  Resources/Changelog/Changelog.yml
  Resources/Locale/en-US/construction/construction-categories.ftl
  Resources/Locale/en-US/nuke/nuke-core-container.ftl
  Resources/Locale/en-US/objectives/conditions/steal.ftl
  Resources/Locale/en-US/store/categories.ftl
  Resources/Locale/en-US/store/uplink-catalog.ftl
  Resources/Locale/en-US/tools/tool-qualities.ftl
  Resources/Prototypes/Catalog/Fills/Items/toolboxes.yml
  Resources/Prototypes/Catalog/uplink_catalog.yml
  Resources/Prototypes/Entities/Objects/Misc/plutonium_core.yml
  Resources/Prototypes/Entities/Objects/Tools/syndicate.yml
  Resources/Prototypes/Entities/Structures/Machines/nuke.yml
  Resources/Prototypes/Objectives/objectiveGroups.yml
  Resources/Prototypes/Objectives/stealTargetGroups.yml
  Resources/Prototypes/Objectives/traitor.yml
  Resources/Prototypes/Recipes/Construction/Graphs/structures/nuke.yml
  Resources/Prototypes/Store/categories.yml
  Resources/Prototypes/Store/presets.yml
  Resources/Prototypes/tags.yml
  Resources/Prototypes/tool_qualities.yml
  Resources/Textures/Objects/Misc/nuke_core_container.rsi/closed.png
  Resources/Textures/Objects/Misc/nuke_core_container.rsi/core_closed.png
  Resources/Textures/Objects/Misc/nuke_core_container.rsi/core_open.png
  Resources/Textures/Objects/Misc/nuke_core_container.rsi/inhand-left.png
  Resources/Textures/Objects/Misc/nuke_core_container.rsi/inhand-right.png
  Resources/Textures/Objects/Misc/nuke_core_container.rsi/meta.json
  Resources/Textures/Objects/Misc/nuke_core_container.rsi/open.png
  Resources/Textures/Objects/Misc/plutonium_core.rsi/icon.png
  Resources/Textures/Objects/Misc/plutonium_core.rsi/meta.json
Labels: Changes: Sprites, Changes: UI

#235 Remove Extra Nuke Disk Steal Objective
  Resources/Prototypes/Objectives/objectiveGroups.yml
Labels: No C#
