Repository greystation14/GreyStation14, pull requests merged in 2025-03, with the labels that each got.

#442 Upstream Fixes 3.15.25
  Resources/Locale/en-US/deltav/flavors/flavor-profiles.ftl
  Resources/Locale/en-US/deltav/reagents/meta/consumable/drink/drinks.ftl
  Resources/Locale/en-US/nyanotrasen/reagents/meta/physical-desc.ftl
  Resources/Prototypes/DeltaV/Entities/Objects/Consumable/Drinks/drinks-cartons.yml
  Resources/Prototypes/DeltaV/Entities/Objects/Consumable/Drinks/drinks.yml
  Resources/Prototypes/DeltaV/Flavors/flavors.yml
  Resources/Prototypes/DeltaV/Reagents/Consumable/Drink/drinks.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml
  Resources/Prototypes/Guidebook/rules.yml
  Resources/Textures/DeltaV/Objects/Consumable/Drinks/daiquiri.rsi/fill-1.png
  Resources/Textures/DeltaV/Objects/Consumable/Drinks/daiquiri.rsi/fill-2.png
  Resources/Textures/DeltaV/Objects/Consumable/Drinks/daiquiri.rsi/fill-3.png
  Resources/Textures/DeltaV/Objects/Consumable/Drinks/daiquiri.rsi/icon.png
  Resources/Textures/DeltaV/Objects/Consumable/Drinks/daiquiri.rsi/icon_empty.png
  Resources/Textures/DeltaV/Objects/Consumable/Drinks/daiquiri.rsi/meta.json
  Resources/Textures/DeltaV/Objects/Consumable/Drinks/juiceboxapple.rsi/icon.png
  Resources/Textures/DeltaV/Objects/Consumable/Drinks/juiceboxapple.rsi/icon_open.png
  Resources/Textures/DeltaV/Objects/Consumable/Drinks/juiceboxapple.rsi/meta.json
  Resources/Textures/DeltaV/Objects/Consumable/Drinks/juiceboxchocolate.rsi/icon.png
  Resources/Textures/DeltaV/Objects/Consumable/Drinks/juiceboxchocolate.rsi/icon_open.png
  Resources/Textures/DeltaV/Objects/Consumable/Drinks/juiceboxchocolate.rsi/meta.json
  Resources/Textures/DeltaV/Objects/Consumable/Drinks/juiceboxgrape.rsi/icon.png
  Resources/Textures/DeltaV/Objects/Consumable/Drinks/juiceboxgrape.rsi/icon_open.png
  Resources/Textures/DeltaV/Objects/Consumable/Drinks/juiceboxgrape.rsi/meta.json
  Resources/Textures/DeltaV/Objects/Consumable/Drinks/juiceboxorange.rsi/icon.png
  Resources/Textures/DeltaV/Objects/Consumable/Drinks/juiceboxorange.rsi/icon_open.png
  Resources/Textures/DeltaV/Objects/Consumable/Drinks/juiceboxorange.rsi/meta.json
  Resources/Textures/DeltaV/Objects/Consumable/Drinks/juiceboxpineapple.rsi/icon.png
  Resources/Textures/DeltaV/Objects/Consumable/Drinks/juiceboxpineapple.rsi/icon_open.png
  Resources/Textures/DeltaV/Objects/Consumable/Drinks/juiceboxpineapple.rsi/meta.json
Labels: Changes: Sprites, Changes: No C#, size/M, S: Untriaged

#443 Revert Upstream Pump Shotgun
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Shotguns/shotguns.yml
  Resources/Prototypes/GreyStation/Entities/Objects/Weapons/Guns/Shotguns/shotguns.yml
  Resources/Textures/GreyStation/Objects/Weapons/Guns/Shotguns/pump.rsi/bolt-open.png
  Resources/Textures/GreyStation/Objects/Weapons/Guns/Shotguns/pump.rsi/equipped-BACKPACK.png
  Resources/Textures/GreyStation/Objects/Weapons/Guns/Shotguns/pump.rsi/equipped-SUITSTORAGE.png
  Resources/Textures/GreyStation/Objects/Weapons/Guns/Shotguns/pump.rsi/icon.png
  Resources/Textures/GreyStation/Objects/Weapons/Guns/Shotguns/pump.rsi/meta.json
  Resources/Textures/GreyStation/Objects/Weapons/Guns/Shotguns/pump_inhands_64x.rsi/inhand-left.png
  Resources/Textures/GreyStation/Objects/Weapons/Guns/Shotguns/pump_inhands_64x.rsi/inhand-right.png
  Resources/Textures/GreyStation/Objects/Weapons/Guns/Shotguns/pump_inhands_64x.rsi/meta.json
  Resources/Textures/GreyStation/Objects/Weapons/Guns/Shotguns/pump_inhands_64x.rsi/wielded-inhand-left.png
  Resources/Textures/GreyStation/Objects/Weapons/Guns/Shotguns/pump_inhands_64x.rsi/wielded-inhand-right.png
Labels: Changes: Sprites, Changes: No C#, size/S, S: Untriaged

#339 add knuckleduster functionality
  Content.Shared/GreyStation/Clothing/ClothingPreventsWieldingComponent.cs
  Content.Shared/GreyStation/Clothing/ClothingPreventsWieldingSystem.cs
  Content.Shared/GreyStation/Weapons/Melee/NoHeavyAttacksComponent.cs
  Content.Shared/GreyStation/Weapons/Melee/NoHeavyAttacksSystem.cs
  Content.Shared/Weapons/Melee/SharedMeleeWeaponSystem.cs
  Resources/Prototypes/GreyStation/Entities/Objects/Weapons/Melee/knuckle_dusters.yml
Labels: size/M

#445 Merge Upstream 3.16.25
  Content.IntegrationTests/Tests/GameRules/NukeOpsTest.cs
  Resources/Changelog/Changelog.yml
  Resources/Credits/GitHub.txt
  Resources/Prototypes/Entities/Effects/puddle.yml
  Resources/Prototypes/Entities/Structures/Machines/holopad.yml
  Resources/Prototypes/GameRules/events.yml
  Resources/Prototypes/Recipes/Lathes/Packs/service.yml
  Resources/ServerInfo/Guidebook/ServerRules/SpaceLaw/SpaceLaw.xml
Labels: size/S, S: Untriaged, S: Merge Conflict

#449 Merge Upstream 3.20.25
  Content.Server/Body/Systems/ThermalRegulatorSystem.cs
  Resources/Changelog/Changelog.yml
Labels: size/S, S: Untriaged, S: Merge Conflict

#446 Port Flip emote from Wizden
  Content.Client/GreyStation/Flip/FlipAnimationSystem.cs
  Content.Server/GreyStation/Flip/FlipAnimationSystem.cs
  Content.Shared/GreyStation/Flip/FlipAnimationComponent.cs
  Content.Shared/GreyStation/Flip/SharedFlipAnimationSystem.cs
  Resources/Locale/en-US/chat/emotes.ftl
  Resources/Locale/en-US/greystation/chat/emotes.ftl
  Resources/Prototypes/Entities/Mobs/base.yml
  Resources/Prototypes/GreyStation/Voice/speech_emotes.yml
  Resources/Textures/GreyStation/Interface/Emotes/attributions.yml
  Resources/Textures/GreyStation/Interface/Emotes/flip.png
Labels: size/M, S: Untriaged

#453 Merge Upstream 3.20.25 2
  Content.Client/UserInterface/Systems/Ghost/Widgets/GhostGui.xaml.cs
  Content.Shared/CCVar/CCVars.Playtest.cs
  Content.Shared/Damage/Systems/DamageableSystem.cs
  Content.Shared/Damage/Systems/StaminaSystem.cs
  Content.Shared/Mobs/Systems/MobStateSystem.Subscribers.cs
  Content.Shared/Mobs/Systems/MobStateSystem.cs
  Resources/Changelog/Changelog.yml
  Resources/Locale/en-US/cvar/cvar-help.ftl
  Resources/Prototypes/ai_factions.yml
Labels: Changes: UI, size/S, S: Untriaged, S: Merge Conflict

#455 fix build realer
  Content.Server/GreyStation/Hailer/DeathgaspMaskSystem.cs
  Content.Shared/GreyStation/Hailer/DeathgaspMaskComponent.cs
  Content.Shared/GreyStation/Hailer/SharedHailerSystem.cs
Labels: size/S, S: Untriaged

#456 Reverts 1:1 portview (for now)
  Content.Client/Gameplay/GameplayState.cs
  Content.Client/UserInterface/Systems/Viewport/ViewportUIController.cs
Labels: size/S, S: Untriaged

#458 Merge Upstream 3.23.25
  .github/workflows/benchmarks.yml
  .github/workflows/build-docfx.yml
  .github/workflows/build-map-renderer.yml
  .github/workflows/build-test-debug.yml
  .github/workflows/check-crlf.yml
  .github/workflows/publish.yml
  .github/workflows/rsi-diff.yml
  .github/workflows/test-packaging.yml
  .github/workflows/update-credits.yml
  .github/workflows/validate-rgas.yml
  .github/workflows/validate-rsis.yml
  .github/workflows/validate_mapfiles.yml
  .github/workflows/yaml-linter.yml
  Content.Client/Alerts/ClientAlertsSystem.cs
  Content.Client/Examine/ExamineButton.cs
  Content.Client/Examine/ExamineSystem.cs
  Content.Client/Verbs/UI/VerbMenuElement.cs
  Content.Client/Verbs/VerbSystem.cs
  Content.IntegrationTests/Tests/PostMapInitTest.cs
  Content.Server/Alert/ServerAlertsSystem.cs
  Content.Server/Hands/Systems/HandsSystem.cs
  Content.Server/Standing/StandingStateSystem.cs
  Content.Server/Verbs/VerbSystem.cs
  Content.Shared/Examine/ExamineSystemShared.Group.cs
  Content.Shared/Standing/StandingStateSystem.cs
  Content.Shared/Verbs/Verb.cs
  Resources/Changelog/Changelog.yml
  Resources/Credits/GitHub.txt
  Resources/Maps/bagel.yml
  Resources/Prototypes/Catalog/Fills/Boxes/service.yml
  Resources/Prototypes/Catalog/Fills/Crates/botany.yml
  Resources/Prototypes/Catalog/Fills/Items/belt.yml
  Resources/Prototypes/Catalog/Fills/Lockers/medical.yml
  Resources/Prototypes/Catalog/Fills/Lockers/service.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/boozeomat.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/chemvend.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/medical.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/nutri.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/wallmed.yml
  Resources/Prototypes/Catalog/thief_toolbox_sets.yml
  Resources/Prototypes/Catalog/uplink_catalog.yml
  Resources/Prototypes/Entities/Clothing/Masks/masks.yml
  Resources/Prototypes/Entities/Clothing/Uniforms/jumpskirts.yml
  Resources/Prototypes/Entities/Clothing/Uniforms/jumpsuits.yml
  Resources/Prototypes/Entities/Markers/Spawners/Random/Department/medical.yml
  Resources/Prototypes/Entities/Markers/Spawners/Random/Food_Drinks/drinks_bottles.yml
  Resources/Prototypes/Entities/Markers/Spawners/Random/Salvage/tables_loot.yml
  Resources/Prototypes/Entities/Objects/Deliveries/deliveries_tables.yml
  Resources/Prototypes/Entities/Objects/Deliveries/package_rare_tables.yml
  Resources/Prototypes/Entities/Objects/Specific/Medical/healing.yml
  Resources/Prototypes/Entities/Objects/Specific/chemistry-bottles.yml
  Resources/Prototypes/Entities/Objects/Tools/handheld_mass_scanner.yml
  Resources/Prototypes/Entities/Objects/Weapons/Melee/knife.yml
  Resources/Prototypes/Procedural/salvage_loot.yml
  Resources/Prototypes/Procedural/salvage_rewards.yml
  Resources/Prototypes/Roles/Jobs/CentComm/emergencyresponseteam.yml
  Resources/Prototypes/Traits/disabilities.yml
  Resources/ServerInfo/Guidebook/Service/Botany.xml
  Resources/migration.yml
Labels: Changes: Map, size/M, S: Untriaged, S: Merge Conflict
